package com.example.chatboat.ui.auth

data class Country(
    val name: String,
    val code: String,
    val flag: String
)

val countries = listOf(
    Country("Afghanistan", "+93", "🇦🇫"),
    Country("Albania", "+355", "🇦🇱"),
    Country("Algeria", "+213", "🇩🇿"),
    Country("Andorra", "+376", "🇦🇩"),
    Country("Angola", "+244", "🇦🇴"),
    Country("Argentina", "+54", "🇦🇷"),
    Country("Armenia", "+374", "🇦🇲"),
    Country("Australia", "+61", "🇦🇺"),
    Country("Austria", "+43", "🇦🇹"),
    Country("Azerbaijan", "+994", "🇦🇿"),
    Country("Bahrain", "+973", "🇧🇭"),
    Country("Bangladesh", "+880", "🇧🇩"),
    Country("Belarus", "+375", "🇧🇾"),
    Country("Belgium", "+32", "🇧🇪"),
    Country("Bolivia", "+591", "🇧🇴"),
    Country("Brazil", "+55", "🇧🇷"),
    Country("Bulgaria", "+359", "🇧🇬"),
    Country("Cambodia", "+855", "🇰🇭"),
    Country("Canada", "+1", "🇨🇦"),
    Country("Chile", "+56", "🇨🇱"),
    Country("China", "+86", "🇨🇳"),
    Country("Colombia", "+57", "🇨🇴"),
    Country("Croatia", "+385", "🇭🇷"),
    Country("Cuba", "+53", "🇨🇺"),
    Country("Cyprus", "+357", "🇨🇾"),
    Country("Czech Republic", "+420", "🇨🇿"),
    Country("Denmark", "+45", "🇩🇰"),
    Country("Egypt", "+20", "🇪🇬"),
    Country("Finland", "+358", "🇫🇮"),
    Country("France", "+33", "🇫🇷"),
    Country("Germany", "+49", "🇩🇪"),
    Country("Greece", "+30", "🇬🇷"),
    Country("Hong Kong", "+852", "🇭🇰"),
    Country("Hungary", "+36", "🇭🇺"),
    Country("Iceland", "+354", "🇮🇸"),
    Country("India", "+91", "🇮🇳"),
    Country("Indonesia", "+62", "🇮🇩"),
    Country("Iran", "+98", "🇮🇷"),
    Country("Iraq", "+964", "🇮🇶"),
    Country("Ireland", "+353", "🇮🇪"),
    Country("Israel", "+972", "🇮🇱"),
    Country("Italy", "+39", "🇮🇹"),
    Country("Jamaica", "+1", "🇯🇲"),
    Country("Japan", "+81", "🇯🇵"),
    Country("Jordan", "+962", "🇯🇴"),
    Country("Kazakhstan", "+7", "🇰🇿"),
    Country("Kenya", "+254", "🇰🇪"),
    Country("Kuwait", "+965", "🇰🇼"),
    Country("Malaysia", "+60", "🇲🇾"),
    Country("Mexico", "+52", "🇲🇽"),
    Country("Morocco", "+212", "🇲🇦"),
    Country("Nepal", "+977", "🇳🇵"),
    Country("Netherlands", "+31", "🇳🇱"),
    Country("New Zealand", "+64", "🇳🇿"),
    Country("Nigeria", "+234", "🇳🇬"),
    Country("Norway", "+47", "🇳🇴"),
    Country("Pakistan", "+92", "🇵🇰"),
    Country("Philippines", "+63", "🇵🇭"),
    Country("Poland", "+48", "🇵🇱"),
    Country("Portugal", "+351", "🇵🇹"),
    Country("Qatar", "+974", "🇶🇦"),
    Country("Romania", "+40", "🇷🇴"),
    Country("Russia", "+7", "🇷🇺"),
    Country("Saudi Arabia", "+966", "🇸🇦"),
    Country("Singapore", "+65", "🇸🇬"),
    Country("South Africa", "+27", "🇿🇦"),
    Country("South Korea", "+82", "🇰🇷"),
    Country("Spain", "+34", "🇪🇸"),
    Country("Sri Lanka", "+94", "🇱🇰"),
    Country("Sweden", "+46", "🇸🇪"),
    Country("Switzerland", "+41", "🇨🇭"),
    Country("Thailand", "+66", "🇹🇭"),
    Country("Turkey", "+90", "🇹🇷"),
    Country("Ukraine", "+380", "🇺🇦"),
    Country("United Arab Emirates", "+971", "🇦🇪"),
    Country("United Kingdom", "+44", "🇬🇧"),
    Country("United States", "+1", "🇺🇸"),
    Country("Vietnam", "+84", "🇻🇳")
)
